In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
df.shape

(150, 5)

In [12]:
data = df.values
X = data[:,0:6]
Y = data[:,4]
print(df)
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]
[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iri

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.4)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[6.3 2.5 4.9 1.5]
 [6.0 2.7 5.1 1.6]
 [7.2 3.2 6.0 1.8]
 [5.4 3.0 4.5 1.5]
 [5.0 3.0 1.6 0.2]
 [6.3 2.7 4.9 1.8]
 [5.8 2.7 4.1 1.0]
 [7.0 3.2 4.7 1.4]
 [4.6 3.1 1.5 0.2]
 [5.4 3.4 1.7 0.2]
 [5.5 3.5 1.3 0.2]
 [6.5 3.0 5.2 2.0]
 [6.4 3.1 5.5 1.8]
 [4.6 3.2 1.4 0.2]
 [5.6 2.8 4.9 2.0]
 [5.5 2.4 3.8 1.1]
 [7.2 3.6 6.1 2.5]
 [5.8 2.7 5.1 1.9]
 [6.1 2.8 4.0 1.3]
 [6.6 2.9 4.6 1.3]
 [5.0 3.5 1.6 0.6]
 [5.6 2.9 3.6 1.3]
 [6.7 3.0 5.2 2.3]
 [6.8 3.2 5.9 2.3]
 [5.9 3.0 5.1 1.8]
 [5.7 2.8 4.1 1.3]
 [6.3 2.9 5.6 1.8]
 [5.7 2.6 3.5 1.0]
 [6.4 2.9 4.3 1.3]
 [5.1 3.5 1.4 0.3]
 [5.7 4.4 1.5 0.4]
 [5.9 3.0 4.2 1.5]
 [5.6 3.0 4.5 1.5]
 [5.1 3.4 1.5 0.2]
 [7.2 3.0 5.8 1.6]
 [5.8 2.7 3.9 1.2]
 [6.4 2.8 5.6 2.1]
 [5.8 4.0 1.2 0.2]
 [6.1 2.9 4.7 1.4]
 [6.9 3.2 5.7 2.3]
 [5.7 2.9 4.2 1.3]
 [5.3 3.7 1.5 0.2]
 [6.8 3.0 5.5 2.1]
 [5.0 3.6 1.4 0.2]
 [6.3 3.3 6.0 2.5]
 [5.5 4.2 1.4 0.2]
 [6.1 2.8 4.7 1.2]
 [6.4 2.8 5.6 2.2]
 [4.9 2.5 4.5 1.7]
 [6.8 2.8 4.8 1.4]
 [5.8 2.6 4.0 1.2]
 [5.9 3.2 4.8 1.8]
 [4.9 3.1 1.

In [64]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(df['species'])
data = df.values
X = data[:,0:6]

In [56]:
from sklearn.svm import SVC
model_svc=SVC()
model_svc.fit(X_train,y_train)

SVC()

In [60]:
predicition1 = model.fit(X_test,y_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(predicition1.predict(X_test),y_test)*100)

100.0


In [55]:
from sklearn.linear_model import LogisticRegression
model_lr=LogisticRegression()
model_lr.fit(X_train,y_train)

LogisticRegression()

In [50]:
predicition2 = model_lr.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(predicition2,y_test)*100)

100.0


In [54]:
from sklearn.tree import DecisionTreeClassifier
model_dtc=DecisionTreeClassifier()
model_dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [61]:
predicition3 = model_dtc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(predicition3,y_test)*100)

95.0
